# Default Docker Compose file (Development)
# For production, use: docker-compose -f docker-compose.prod.yml up

version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: ahmadcahyana-app
    ports:
      - "9002:9002"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  app-network:
    driver: bridge